spring:
  datasource:
    c3p0:
      driver-class: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/spring-security-demo?characterEncoding=utf-8
      user: root
      password: root
      auto-commit-on-close: false
      min-pool-size: 3
      max-pool-size: 9
      max-idle-time: 27
      test-connection-on-checkin: true
      preferred-test-query: SELECT 1